version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build-and-test:
      jobs:
        - Run unit tests
        - Build and Push Docker Image:
            filters:
              branches:
                only: master
            requires:
              - Run unit tests

jobs:
  Run unit tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run unit tests and test coverage
          command: |
            python -m xmlrunner discover -s test -o test_reports
      - store_test_results:
          path: test_reports
  Build and Push Docker Image:
    docker:
      - image: cimg/python:3.9
        auth:
          username: emmaogiji
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build -t emmaogiji/mintelweather:$TAG -t emmaogiji/mintelweather:latest . --build-arg location_key=$LOCATION_API_KEY --build-arg weather_key=$WEATHER_API_KEY
          echo $DOCKERHUB_PASSWORD | docker login -u emmaogiji --password-stdin
          docker push emmaogiji/mintelweather:$TAG
          docker push emmaogiji/mintelweather:latest
